/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AnimationRouteImport } from './routes/animation'
import { Route as LatestRouteImport } from './routes/latest'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SongRouteImport } from './routes/song'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as WatchIdRouteImport } from './routes/watch.$id'
import { Route as ApiPayActionRouteImport } from './routes/api/pay/$action'
import { Route as ApiPublicDownloadRouteImport } from './routes/api/public/download'
import { Route as ApiR2ActionRouteImport } from './routes/api/r2/$action'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimationRoute = AnimationRouteImport.update({
  id: '/animation',
  path: '/animation',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestRoute = LatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SongRoute = SongRouteImport.update({
  id: '/song',
  path: '/song',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPayActionRoute = ApiPayActionRouteImport.update({
  id: '/api/pay/$action',
  path: '/api/pay/$action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDownloadRoute = ApiPublicDownloadRouteImport.update({
  id: '/api/public/download',
  path: '/api/public/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiR2ActionRoute = ApiR2ActionRouteImport.update({
  id: '/api/r2/$action',
  path: '/api/r2/$action',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/animation': typeof AnimationRoute
  '/latest': typeof LatestRoute
  '/movies': typeof MoviesRoute
  '/profile': typeof ProfileRoute
  '/series': typeof SeriesRoute
  '/settings': typeof SettingsRoute
  '/song': typeof SongRoute
  '/trending': typeof TrendingRoute
  '/watchlist': typeof WatchlistRoute
  '/watch/$id': typeof WatchIdRoute
  '/api/pay/$action': typeof ApiPayActionRoute
  '/api/public/download': typeof ApiPublicDownloadRoute
  '/api/r2/$action': typeof ApiR2ActionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/animation': typeof AnimationRoute
  '/latest': typeof LatestRoute
  '/movies': typeof MoviesRoute
  '/profile': typeof ProfileRoute
  '/series': typeof SeriesRoute
  '/settings': typeof SettingsRoute
  '/song': typeof SongRoute
  '/trending': typeof TrendingRoute
  '/watchlist': typeof WatchlistRoute
  '/watch/$id': typeof WatchIdRoute
  '/api/pay/$action': typeof ApiPayActionRoute
  '/api/public/download': typeof ApiPublicDownloadRoute
  '/api/r2/$action': typeof ApiR2ActionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/animation': typeof AnimationRoute
  '/latest': typeof LatestRoute
  '/movies': typeof MoviesRoute
  '/profile': typeof ProfileRoute
  '/series': typeof SeriesRoute
  '/settings': typeof SettingsRoute
  '/song': typeof SongRoute
  '/trending': typeof TrendingRoute
  '/watchlist': typeof WatchlistRoute
  '/watch/$id': typeof WatchIdRoute
  '/api/pay/$action': typeof ApiPayActionRoute
  '/api/public/download': typeof ApiPublicDownloadRoute
  '/api/r2/$action': typeof ApiR2ActionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/agent'
    | '/animation'
    | '/latest'
    | '/movies'
    | '/profile'
    | '/series'
    | '/settings'
    | '/song'
    | '/trending'
    | '/watchlist'
    | '/watch/$id'
    | '/api/pay/$action'
    | '/api/public/download'
    | '/api/r2/$action'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/agent'
    | '/animation'
    | '/latest'
    | '/movies'
    | '/profile'
    | '/series'
    | '/settings'
    | '/song'
    | '/trending'
    | '/watchlist'
    | '/watch/$id'
    | '/api/pay/$action'
    | '/api/public/download'
    | '/api/r2/$action'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/agent'
    | '/animation'
    | '/latest'
    | '/movies'
    | '/profile'
    | '/series'
    | '/settings'
    | '/song'
    | '/trending'
    | '/watchlist'
    | '/watch/$id'
    | '/api/pay/$action'
    | '/api/public/download'
    | '/api/r2/$action'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AgentRoute: typeof AgentRoute
  AnimationRoute: typeof AnimationRoute
  LatestRoute: typeof LatestRoute
  MoviesRoute: typeof MoviesRoute
  ProfileRoute: typeof ProfileRoute
  SeriesRoute: typeof SeriesRoute
  SettingsRoute: typeof SettingsRoute
  SongRoute: typeof SongRoute
  TrendingRoute: typeof TrendingRoute
  WatchlistRoute: typeof WatchlistRoute
  WatchIdRoute: typeof WatchIdRoute
  ApiPayActionRoute: typeof ApiPayActionRoute
  ApiPublicDownloadRoute: typeof ApiPublicDownloadRoute
  ApiR2ActionRoute: typeof ApiR2ActionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animation': {
      id: '/animation'
      path: '/animation'
      fullPath: '/animation'
      preLoaderRoute: typeof AnimationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest': {
      id: '/latest'
      path: '/latest'
      fullPath: '/latest'
      preLoaderRoute: typeof LatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/song': {
      id: '/song'
      path: '/song'
      fullPath: '/song'
      preLoaderRoute: typeof SongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pay/$action': {
      id: '/api/pay/$action'
      path: '/api/pay/$action'
      fullPath: '/api/pay/$action'
      preLoaderRoute: typeof ApiPayActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/download': {
      id: '/api/public/download'
      path: '/api/public/download'
      fullPath: '/api/public/download'
      preLoaderRoute: typeof ApiPublicDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/r2/$action': {
      id: '/api/r2/$action'
      path: '/api/r2/$action'
      fullPath: '/api/r2/$action'
      preLoaderRoute: typeof ApiR2ActionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AgentRoute: AgentRoute,
  AnimationRoute: AnimationRoute,
  LatestRoute: LatestRoute,
  MoviesRoute: MoviesRoute,
  ProfileRoute: ProfileRoute,
  SeriesRoute: SeriesRoute,
  SettingsRoute: SettingsRoute,
  SongRoute: SongRoute,
  TrendingRoute: TrendingRoute,
  WatchlistRoute: WatchlistRoute,
  WatchIdRoute: WatchIdRoute,
  ApiPayActionRoute: ApiPayActionRoute,
  ApiPublicDownloadRoute: ApiPublicDownloadRoute,
  ApiR2ActionRoute: ApiR2ActionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
